### ISSUE TITLE
Feature request: fuzzing absolute URLs

### ISSUE THREAD

**Issue by 0xAwali** [sw33tLie/uff#1]
Hi sw33tLie ,

it's possible to let this fork fuzzing absolute URL e.g.

```
GET http://FUZZ HTTP/1.1
Host: example.com
```

thanks

**Comment by sw33tLie** [comment]
Hi,
I just added it.

```
uff -u http://example.com -w wordlist.txt -opaque "http://FUZZ/"
```

-opaque allows you to control the part between the method and the http version:

method OPAQUE HTTP/1.1

Hope this helps!

**Comment by Kr1shna4garwal** [comment]
Hey @sw33tLie! Thank you for adding this.

Normally, it's working as intended, but When I'm trying to proxying the uff's traffic to burp, i'm not getting `GET http://target.com HTTP/1.1` in the url but getting "/", it would be nice if you could guide me on this.

command i'm using:
```
uff -ac -v -mc all -c -u "URL_TO_FUZZ" -w urls/http_webservers_urls.txt:URL_TO_FUZZ -w kugvGkvIDS.txt:SDKR -opaque "http://SDKR/" -x http://127.0.0.1:8080
```

Thanks

**Comment by sw33tLie** [comment]
You're right, I've been aware of this for a while.
I use net/http's .Opaque override to allow absolute URI fuzzing, and that happens when proxying (it's kinda the whole point of proxying, actually).

I'll see if there's something I can do to avoid it.
Thanks!
